services:
  idp:
    build: .
    image: ao-images/ao-idp-server:latest
    pull_policy: never
    container_name: ao-idp
    ports:
      - "7000:7000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      IDP_ISSUER: ${IDP_ISSUER}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
    volumes:
      - ao-idp-postgres:/var/lib/postgresql/data
    networks:
      - ao-net
      - default
    restart: unless-stopped

volumes:
  ao-idp-postgres:

networks:
  ao-net:
    external: true